import pandas as pd
import numpy as np
from pathlib import Path
from typing import Tuple, Optional

from src.utils.paths import load_paths
from src.utils.logging import setup_logger
from src.features.extract import load_feature_config, extract_features_from_flows
from src.splits.io import load_splits

logger = setup_logger()


def apply_split_lists(
        df: pd.DataFrame,
        train_list: Path,
        val_list: Path,
        test_list: Path,
        *,
        split_col: str = "split"
) -> pd.DataFrame:
    """
    Applies canonical split lists to VNAT/ISCX based on capture_id (PCAP filenames).
    """
    splits = load_splits(train_list, val_list, test_list)

    cap_to_split = {}
    for split_name, caps in splits.items():
        for cid in caps:
            cap_to_split[str(cid)] = split_name

    out = df.copy()
    out["capture_id"] = out["capture_id"].astype(str)
    out[split_col] = out["capture_id"].map(cap_to_split)

    # We drop rows not explicitly assigned to a split for ISCX/VNAT consistency
    out = out.dropna(subset=[split_col])
    return out


def load_and_prepare_data(
        config_path: Optional[Path] = None,
        vnat_only: bool = False
) -> pd.DataFrame:
    """
    Loads VNAT, ISCX, and USBVPN, aligns them into a single Multi-Domain pool,
    and ensures Capture-Level separation (No Leakage).
    """
    paths = load_paths()
    if config_path is None:
        config_path = paths.configs_dir / "features.yaml"

    cfg = load_feature_config(config_path)
    all_dfs = []

    # --- 1. VNAT (PCAP Domain) ---
    logger.info("Loading VNAT (PCAP-based)...")
    vnat_path = paths.data_processed_dir / "vnat" / "flows.parquet"
    if vnat_path.exists():
        vnat_flows = pd.read_parquet(vnat_path)
        vnat_feats = extract_features_from_flows(vnat_flows, cfg)
        vnat_feats["dataset"] = "vnat"
        vnat_feats = apply_split_lists(
            vnat_feats,
            paths.data_splits / "vnat_train_captures.txt",
            paths.data_splits / "vnat_val_captures.txt",
            paths.data_splits / "vnat_test_captures.txt",
        )
        all_dfs.append(vnat_feats)

    if vnat_only:
        return all_dfs[0] if all_dfs else pd.DataFrame()

    # --- 2. ISCX (PCAP Domain) ---
    logger.info("Loading ISCX (PCAP-based)...")
    iscx_path = paths.data_processed_dir / "iscx" / "flows.parquet"
    if iscx_path.exists():
        iscx_flows = pd.read_parquet(iscx_path)
        iscx_feats = extract_features_from_flows(iscx_flows, cfg)
        iscx_feats["dataset"] = "iscx"
        iscx_feats = apply_split_lists(
            iscx_feats,
            paths.data_splits / "iscx_train_captures.txt",
            paths.data_splits / "iscx_val_captures.txt",
            paths.data_splits / "iscx_test_captures.txt",
        )
        all_dfs.append(iscx_feats)

    # --- 3. USBVPN (JSON Domain - The "Cheap Fix" Integration) ---
    logger.info("Loading USBVPN (JSON-based)...")
    usbvpn_path = paths.data_processed_dir / "usbvpn" / "flows.parquet"
    if usbvpn_path.exists():
        usb_feats = pd.read_parquet(usbvpn_path)
        usb_feats["dataset"] = "usbvpn"

        # Validation: Ensure Capture ID is not the generic "combined" string
        unique_caps = usb_feats["capture_id"].nunique()
        if unique_caps == 1 and "usbvpn_combined" in str(usb_feats["capture_id"].iloc[0]):
            logger.warning("USBVPN has only ONE capture_id. Capture-level leakage likely!")

        # Ensure it has a split column (generated by the adapter notebook)
        if "split" not in usb_feats.columns:
            logger.error("USBVPN missing 'split' column. Re-run Notebook 09 with Capture-Level splitting.")

        all_dfs.append(usb_feats)
    else:
        logger.warning(f"USBVPN not found at {usbvpn_path}")

    # --- 4. Final Alignment & Quality Filtering ---
    df_all = pd.concat(all_dfs, ignore_index=True)

    # Universal Quality Filter: Only keep flows with enough packets
    if "q_min_packets_ok" in df_all.columns:
        df_all = df_all[df_all["q_min_packets_ok"] == 1].copy()

    # Clean up column types for XGBoost/LightGBM
    df_all["split"] = df_all["split"].astype(str)
    df_all["dataset"] = df_all["dataset"].astype(str)
    df_all["label"] = df_all["label"].astype(int)

    logger.info(f"Multi-Domain Pool Created: {df_all.shape}")
    logger.info(f"Datasets: {df_all['dataset'].value_counts().to_dict()}")
    logger.info(f"Splits: {df_all['split'].value_counts().to_dict()}")

    return df_all