"""Export per-(feature, dataset) raw-space sign-reversal directions to CSV.

Sources (raw, unscaled feature space):
  artifacts/sign_reversal_forensic_audit/feature_effects_by_dataset.csv
  artifacts/sign_reversal_forensic_audit/sign_reversal_final_verdict.csv

Generated by `src/eval/sign_reversal_forensic_audit.py` (which produces the
inputs for Figure 3.9 / Table 3.5 in the thesis).

Output: artifacts/sign_reversal_forensic_audit/tables/sign_reversal_feature_directions.csv
"""
from __future__ import annotations

from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
AUDIT = ROOT / "artifacts" / "sign_reversal_forensic_audit"
EFFECTS = AUDIT / "feature_effects_by_dataset.csv"
VERDICT = AUDIT / "sign_reversal_final_verdict.csv"
OUT_DIR = AUDIT / "tables"
OUT_DIR.mkdir(parents=True, exist_ok=True)
OUT_CSV = OUT_DIR / "sign_reversal_feature_directions.csv"

# Per spec: direction is taken from the standardised mean difference (SMD)
# computed in raw space with pooled std; |SMD| < 0.05 is treated as "weak".
WEAK_SMD = 0.05

FINAL_CATEGORY_MAP = {
    ("VERIFIED REVERSAL", "robust"): "verified_raw_space_reversal",
    ("VERIFIED REVERSAL", "sensitive"): "verified_raw_space_reversal",
    ("LIKELY REVERSAL BUT SENSITIVE", "robust"): "likely_preprocessing_sensitive",
    ("LIKELY REVERSAL BUT SENSITIVE", "sensitive"): "likely_preprocessing_sensitive",
    ("POSSIBLE ARTIFACT", "robust"): "possible_preprocessing_artifact",
    ("POSSIBLE ARTIFACT", "sensitive"): "possible_preprocessing_artifact",
    ("NO REVERSAL", "robust"): "no_reversal",
    ("NO REVERSAL", "sensitive"): "no_reversal",
}


def direction_from_smd(smd: float) -> str:
    if pd.isna(smd):
        return "weak"
    if abs(smd) < WEAK_SMD:
        return "weak"
    return "+" if smd > 0 else "-"


def main() -> None:
    eff = pd.read_csv(EFFECTS)
    ver = pd.read_csv(VERDICT)

    # Sanity: only raw transform expected in this artifact.
    assert set(eff["transform_name"].unique()) == {"raw"}, (
        "Expected only raw-space rows in feature_effects_by_dataset.csv"
    )

    rows = []
    for _, r in eff.iterrows():
        cliff = float(r["cliffs_delta"])
        # SMD == Cohen's d in this audit (raw-space, pooled std).
        smd = float(r["cohen_d"])
        auc = float(r["auc"])
        feat = str(r["feature"])
        ds = str(r["dataset"])

        vrow = ver[ver["feature"] == feat]
        if vrow.empty:
            reversal_status = "inconclusive"
            note = "no verdict row for feature"
        else:
            v = vrow.iloc[0]
            cat = str(v["final_category"]).strip()
            tag = str(v["robustness_tag"]).strip()
            reversal_status = FINAL_CATEGORY_MAP.get(
                (cat, tag), "inconclusive"
            )
            note_bits = [f"final_category={cat}", f"robustness={tag}"]
            if not bool(v["reversal_raw_space"]):
                note_bits.append("not_reversing_in_raw_space")
            if bool(v["reversal_introduced_only_after_scaling"]):
                note_bits.append("reversal_introduced_only_after_scaling")
            note = "; ".join(note_bits)

        rows.append(
            {
                "feature": feat,
                "dataset": ds,
                "smd": smd,
                "single_feature_auc": auc,
                "cliffs_delta": cliff,
                "direction": direction_from_smd(smd),
                "reversal_status": reversal_status,
                "notes": note,
            }
        )

    out = pd.DataFrame(rows)
    # Order: verified reversers first, then sensitive, then artifacts; then by feature/dataset.
    status_order = {
        "verified_raw_space_reversal": 0,
        "likely_preprocessing_sensitive": 1,
        "possible_preprocessing_artifact": 2,
        "no_reversal": 3,
        "inconclusive": 4,
    }
    out["_sort"] = out["reversal_status"].map(status_order).fillna(99)
    out = out.sort_values(["_sort", "feature", "dataset"]).drop(columns="_sort")

    out.to_csv(OUT_CSV, index=False)
    print(f"Wrote {len(out)} rows to: {OUT_CSV}")


if __name__ == "__main__":
    main()



